### ISSUE TITLE
Need to add variable to change Maven Mirror URL

### ISSUE THREAD

**Issue by rmiguelito** [OpenLiberty/open-liberty-s2i#13]
Hi
Please add support to change the base URL of a mirror used for retrieving artifacts via environment variable like MAVEN_MIRROR_URL.
It would be very useful for disconnected clusters.

**Comment by brenthdaniel** [comment]
Hi,
MAVEN_MIRROR_URL can now be specified at s2i build time. 
`s2i build ... --env MAVEN_MIRROR_URL=...`
