### ISSUE TITLE
Provide a s2i image for Java 17

### ISSUE THREAD

**Issue by sasaken555** [OpenLiberty/open-liberty-s2i#71]
Can this s2i image provide Java 17 based s2i image?
Java 17 is a LTS Java version, so s2i users will choose Java 17 supported builder/runner image.

**Comment by kevin-ortega** [comment]
@sasaken555 I will look into creating a Java 17 based s2i image but will make no promises.

**Comment by kevin-ortega** [comment]
@JamesBlandford @sasaken555 
s2i images with Java17 are published to dockerhub and icr.   Please check them out and validate they are what you are looking for.

**Comment by JamesBlandford** [comment]
thank you kevin! very speedy response. will pull the image and report back

**Comment by sasaken555** [comment]
@kevin-ortega Thank you for your great work. It works fine!

**Comment by kevin-ortega** [comment]
reopening to feature approval process.

**Comment by malincoln** [comment]
Alasdair agreed okay to close.
