### ISSUE TITLE
oc import-image -n openshift openliberty:latest

### ISSUE THREAD

**Issue by ghost** [OpenLiberty/open-liberty-s2i#9]
I have update the imagestream via: oc import-image -n openshift openliberty:19.0.0.6 which leveled the imagestream up to version 19.0.0.9. The generated liberty container image then got levelled up to version 19.0.0.9

It would be even better when a development environment could stay up to date using the oc import-image -n openshift openliberty:latest command.

**Comment by brenthdaniel** [comment]
The image stream will now use the latest image by default
