### ISSUE TITLE
Java 21 support

### ISSUE THREAD

**Issue by appiepollo14** [OpenLiberty/open-liberty-s2i#91]
Hi there,

As java 21 has been released for a while now, when will there be an s2i image supporting this?

Kind regards, Asjer

**Comment by kevin-ortega** [comment]
Hi @appiepollo14,

Adding support for Java 21 is in our roadmap but unfortunately I don't have a date when that work will be completed.

**Comment by kevin-ortega** [comment]
Hi @appiepollo14.
Quick update, I've started working on adding Java 21 support.    The work is about done but I need to wait until Open Liberty releases version 24.0.0.1 images with Java 21.  That will hopefully happen next week.   s2i images should follow shortly after. I'll update this issue when the s2i images are published.

**Comment by appiepollo14** [comment]
@kevin-ortega keep up the great work. Am I correct this project is the project behind the s2i images available at ibm image registry?

**Comment by kevin-ortega** [comment]
@appiepollo14 Yes, this project creates the open liberty s2i images published in the container registry.

**Comment by kevin-ortega** [comment]
@appiepollo14 s2i images with 24.0.0.1 and Java 21 are published to docker:  https://hub.docker.com/r/ibmcom/websphere-liberty-s2i/tags

I'm working on icr.

**Comment by kevin-ortega** [comment]
@appiepollo14 s2i images are published to ICR.  

```
icr.io/appcafe/open-liberty-s2i:24.0.0.1-java21           
icr.io/appcafe/open-liberty-s2i:24.0.0.1-runtime-java21  
```

Try them out!
